### PR TITLE
Updates to turbine simulation post-processing

### PR DESCRIPTION
**Pull request by jfrederik-nrel**
- Added turbine post-processing functions
- Added wake analysis tools:
     - Obtaining wake profiles from plane data
     - Fitting (single or double) Gaussian to wake profiles
     - Determining wake centerline
 - 02_post_process_turbine_sim updated to showcase new functionality

### CODE REVIEW

**Review by misi9170 — APPROVED** [review]
@jfrederik-nrel This looks good. My only minor comment is that, for consistency across our codes, we usually specify Boolean options as `True` or `False` rather than as integers `1` and `0`; so, consider updating the defaults to, for instance, `verbose=True`. 

I've gone ahead and approved.

**Comment by paulf81** [comment]
Testing this now, just added scipy as a requirement, also is this file very large @jfrederik-nrel 

undError: [Errno 2] No such file or directory: '/projects/ssc/jfrederi/amr-wind-runs/precursor-reverted/baseline_8ms/post_processing/samplingPlane14400.nc'

Could it be included (maybe if we reduce to the minimum) so that the example can run?

**Comment by paulf81** [comment]
> @jfrederik-nrel This looks good. My only minor comment is that, for consistency across our codes, we usually specify Boolean options as `True` or `False` rather than as integers `1` and `0`; so, consider updating the defaults to, for instance, `verbose=True`.
> 
> I've gone ahead and approved.

I agree with True / False over 1/0 for consistency

**Comment by jfrederik-nrel** [comment]
> Testing this now, just added scipy as a requirement, also is this file very large @jfrederik-nrel
> 
> undError: [Errno 2] No such file or directory: '/projects/ssc/jfrederi/amr-wind-runs/precursor-reverted/baseline_8ms/post_processing/samplingPlane14400.nc'
> 
> Could it be included (maybe if we reduce to the minimum) so that the example can run?

It is pretty big (2.3GB). But that's a pretty long simulation (3600s). We could consider running some shorter example simulations and adding those to the repo...

**Comment by paulf81** [comment]
Yeah, or maybe we leave it as is, people can review it as executed online, and then take the code snippets and apply to their own files, maybe we go for that for now and in the future try to make some very minimal .nc file we can use for short examples and test scripts

**Comment by jfrederik-nrel** [comment]
Verbose to boolean has been updated. Agree with @paulf81 that we can potentially add an example file, but that is not super straightforward as we need to run an AMR simulation first to do so.

**Pull request merged**
